### ISSUE TITLE
tennis显卡980算力不匹配

### ISSUE THREAD

**Issue by lineralq** [SeetaFace6Open/index#1]
编译GPU版本tennis调用显卡GTX980运行时报显卡算力不匹配，请问下如何设置显卡算力？
具体报错内容：
Got cuda error(209) no kernel image is available for execution on the device
terminate called after throwing an instance of 'ts::api::Exception'
  what():  [src/kernels/gpu/cast.cu:63]: Got cuda error(209) no kernel image is available for execution on the device
已放弃 (核心已转储)

**Comment by seetafaceengine** [comment]
关于cuda架构，TenniS默认最低架构是53（10xx以上），大家可以参考TenniS/camke/use_cuda.cmake进行配置。使用TS_CUDA_ARCH选项来指定需要运行的架构。有架构不兼容的代码就要各位先自行解决了。

**Comment by lineralq** [comment]
好的，谢谢。
