### ISSUE TITLE
载入人脸检测模型时出错

### ISSUE THREAD

**Issue by hengC-137** [SeetaFace6Open/index#14]
你好，我在加载人脸检测模型的时候出了问题，以下是我创建detector实例的代码：
`std::string file = "E:/ProjectsCpp/template/index/FaceBoxes/example/face_detector.csta";`
    `seeta::ModelSetting setting;`
    `setting.append(file);`
    `setting.set_device(seeta::ModelSetting::CPU);`
    `setting.set_id(0);`
    `seeta::FaceDetector* new_fd = new seeta::FaceDetector(setting);`

这部分的代码我是按Demo写的。
以下是报错的内容。

ERROR: [src\orz\codec\json.cpp:290]: syntax error: unrecognized symbol f
ERROR: [FaceDetector.cpp:138]: Model: / must be dict
我没有修改过里面的代码，模型文件也是从DropBox直接下载下来的。
请问这是可能是什么原因导致的呢？谢谢！

**Comment by 0xRookie** [comment]
请问怎么解决的

**Comment by yuxiangxin** [comment]
添加定义 SEETA_MODEL_ENCRYPT
```c++
// model_helper.h 
 
 #ifdef SEETA_MODEL_ENCRYPT
/**
 * @param modelfile the model file path, support json, sta, csta type model file.
 * @return return the model's jub object
*/
orz::jug get_model_jug(const char * modelfile) {
    return SeetaLock_GetModelJug(modelfile);
}

 
#else
/**
 * @param modelfile the model file path, support json, sta type model file.
 * @return return the model's jub object
*/
orz::jug get_model_jug(const char * modelfile) {
    std::string strfile(modelfile);
    orz::ModelFileInputStream stream(strfile);
    return stream.read_jug();
}
```

**Comment by TheLittleBoy** [comment]
加了，还是报 orz::Exception: [FaceDetector.cpp:138]: Model: / must be dict
