### ISSUE TITLE
‘m_allocator’ was not declared in this scope 编译OpenRoleZoo模块

### ISSUE THREAD

**Issue by AllenY1987** [SeetaFace6Open/index#3]
编译OpenRoleZoo模块时出现‘m_allocator’ was not declared in this scope

**Comment by AllenY1987** [comment]
pot.h中添加下面代码解决问题
#include <functional>

**Comment by zengwbz** [comment]
#include  what???

**Comment by Lin-MZ** [comment]
#include <functional>

**Comment by brucehu** [comment]
修改 pot.h 文件 加入
#include <functional>

**Comment by brucehu** [comment]
修改 pot.h 文件 加入
#include < functional >
