### ISSUE TITLE
有人能成功使用68点识别吗

### ISSUE THREAD

**Issue by jyk1987** [SeetaFace6Open/index#30]
我使用5点正常
但是68点张三识别成李四
是不是放出来的模型有问题啊？有人68点成功吗？

**Comment by Martin-HZK** [comment]
是怎么解决的呀？我还出现demo切换模型到face_landmarker_pts68.csta模型的时候程序直接退出的情况。报错还是在FaceRecognizer.cpp的源码中的库里面的问题，好奇怪
